version: '3'

services:

  currency-conversion-api:
    image: fabbo/currency-conversion-api:latest
    container_name: currency-conversion-api
    env_file:
      - ./currency_conversion_api.env
    #volumes:
      #- ./certs:/certs:ro  # Uncomment for HTTPS
    ports:
      - "8070:80"
      #- "8071:443"  # Uncomment for HTTPS
    restart: unless-stopped
    networks:
      - currency-conversion-api-net

networks:
  currency-conversion-api-net:
