version: '3'

services:

  api:
    build:
      context: djangorest
      dockerfile: Dockerfile
    env_file:
      - ./currency_conversion_api.env
    volumes:
      - ./logs:/var/log/api
      - ./certs:/certs:ro
    depends_on:
      - db
    ports:
      - "8070:443"
    restart: unless-stopped
    networks:
      - currency_conversion_api_net

  db:
    image: postgres:15.1
    env_file:
      - ./postgres_db.env
    ports:
      - "31700:5432"
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - currency_conversion_api_net

  pgadmin:
    image: dpage/pgadmin4:6.20
    env_file:
      - ./pgadmin.env
    ports:
      - "31750:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - currency_conversion_api_net

networks:
  currency_conversion_api_net:
    name: currency_conversion_api_net
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"