apiVersion: v1
kind: Service
metadata:
  name: currency-conversion-api-service
  namespace: default
  labels:
    app: currency-conversion-api
spec:
  selector:
    app: currency-conversion-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32090
